FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY . .

COPY . .

RUN dotnet restore MyMVCApp.csproj
RUN dotnet build MyMVCApp.csproj -c Release
RUN dotnet publish MyMVCApp.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "MyMVCApp.dll"]
